#! /usr/bin/env python
# encoding: utf-8

import os

######################
###### options #######
######################
def options (opt):
  pass

######################
##### configure ######
######################
def configure (conf):
	if conf.env["LP_LIB"]:
		conf.fatal ("Trying to configure a second library for LP")
	conf.env["LP_LIB"] = "NONE"

	conf.env.IBEX_LP_LIB_INCLUDES = "#define __IBEX_NO_LP_SOLVER__"
	conf.env.IBEX_LP_LIB_EXTRA_ATTRIBUTES = ""
