#! /usr/bin/env python
# encoding: utf-8

from waflib import Logs

def options (opt):
	opt.add_option ("--with-slam", action="store_true", dest="WITH_SLAM",
			help = "Use SLAM plugin (from ENSTA Bretagne)")

def configure (conf):
	conf.env.WITH_SLAM = conf.options.WITH_SLAM
		
	if not conf.env.WITH_SLAM: 
		return
	
	Logs.pprint ("BLUE", "Configure the SLAM plugin")
	
	# add SLAM plugin include directory
	conf.env.append_unique("INCLUDES","../../plugins/slam/src")

def build (bld):
		
	if not bld.env.WITH_SLAM: 
		return
	
	Logs.pprint ("BLUE", "Build the SLAM plugin")

	# add SLAM plugin sources
	bld.env.IBEX_SRC.extend(bld.path.ant_glob ("src/**/ibex_*.cpp"))
	# add SLAM plugin headers
	bld.env.IBEX_HDR.extend(bld.path.ant_glob ("src/**/ibex_*.h"))
	
