#! /usr/bin/env python
# encoding: utf-8

import ibexutils
import os, sys
from waflib import Logs

######################
###### options #######
######################
def options (opt):
	grp_name = "Profil/Bias options (when --with-interval-lib=bias is used)"
	grp = opt.add_option_group (grp_name)
	grp.add_option ("--bias-dir", action="store", type="string", dest="BIAS_PATH", default = "", help = "location of the Profil/Bias lib and include directories")

######################
##### configure ######
######################
def configure (conf):
	if conf.env["INTERVAL_LIB"]:
		conf.fatal ("Trying to configure a second library for interval arithmetic")
	conf.env["INTERVAL_LIB"] = "BIAS"
	if conf.options.BIAS_PATH != "":
		bias_dir = conf.options.BIAS_PATH
		conf.msg ("Using library bias from", bias_dir)
		bias_include = os.path.join (bias_dir, "include")
		bias_lib = os.path.join (bias_dir, "lib")
		conf.env.append_unique ("INCLUDES", bias_include)
		conf.env.append_unique ("LIBPATH", bias_lib)
		conf.env.append_unique ("INCLUDES_IBEX_DEPS", bias_include)
		conf.env.append_unique ("LIBPATH_IBEX_DEPS", bias_lib)

	# Test that bias can be found
	conf.check_cxx (header_name = "BIAS/BiasF.h", uselib_store="BIAS")
	biaslibs = ["Profil", "Bias", "lr"]
	conf.check_cxx (lib = biaslibs, uselib_store = "BIAS")
	conf.env.append_unique ("IBEX_DEPS", ["BIAS"])
	conf.env.prepend_value ("LIB_IBEX_DEPS", biaslibs)
