#! /usr/bin/env python
# encoding: utf-8

import os, sys

from waflib import Logs

def options (opt):
	opt.add_option ("--with-optim-MinMax", action="store_true", dest="WITH_OPTIMMINMAX",
			help = "install IbexMiniMax plugin")	
	
def configure (conf):
	conf.env.WITH_OPTIMMINMAX = conf.options.WITH_OPTIMMINMAX
		
	Logs.pprint ("BLUE", "Configure IbexMinMax plugin")
	
	# import utilities
	sys.path.append(conf.srcnode.abspath())
	import ibexutils

	# add include directories
	conf.env.INCLUDES.extend(["../../plugins/optim_minmax/src/%s" % p for p in "tools strategy".split()])
		 

	
def build (bld):

	if not bld.env.WITH_OPTIMMINMAX: 
		return
		
	Logs.pprint ("BLUE", "Build IbexMinMax plugin")
	
	# import utilities
	sys.path.append(bld.srcnode.abspath())
	import ibexutils
	
	# add sources
	bld.env.IBEX_SRC.extend(bld.path.ant_glob ("src/**/ibex_*.cpp"))
	# add headers
	bld.env.IBEX_HDR.extend(bld.path.ant_glob ("src/**/ibex_*.h"))

