#! /usr/bin/env python
# encoding: utf-8

import ibexutils
import os, sys
from waflib import Logs

######################
###### options #######
######################
def options (opt):
	pass # no options for this plugin

######################
##### configure ######
######################
def configure (conf):
	if conf.env["INTERVAL_LIB"]:
		conf.fatal ("Trying to configure a second library for interval arithmetic")
	conf.env["INTERVAL_LIB"] = "DIRECT"

	Logs.warn ("Using interval library direct may not give exact results")

	conf.check_cxx (cxxflags = "-frounding-math", use = [ "IBEX", "ITV_LIB" ],
			uselib_store = "ITV_LIB")
	conf.check_cxx (cxxflags = "-ffloat-store", use = [ "IBEX", "ITV_LIB" ],
			uselib_store = "ITV_LIB")
