################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../plugins/ampl/3rd/amplsolversOLD/arithchk.c \
../plugins/ampl/3rd/amplsolversOLD/asldate.c \
../plugins/ampl/3rd/amplsolversOLD/atof.c \
../plugins/ampl/3rd/amplsolversOLD/auxinfo.c \
../plugins/ampl/3rd/amplsolversOLD/avltree.c \
../plugins/ampl/3rd/amplsolversOLD/b_search.c \
../plugins/ampl/3rd/amplsolversOLD/basename.c \
../plugins/ampl/3rd/amplsolversOLD/bscanf.c \
../plugins/ampl/3rd/amplsolversOLD/com2eval.c \
../plugins/ampl/3rd/amplsolversOLD/comeval.c \
../plugins/ampl/3rd/amplsolversOLD/con1ival.c \
../plugins/ampl/3rd/amplsolversOLD/con2ival.c \
../plugins/ampl/3rd/amplsolversOLD/con2val.c \
../plugins/ampl/3rd/amplsolversOLD/conadj.c \
../plugins/ampl/3rd/amplsolversOLD/conpval.c \
../plugins/ampl/3rd/amplsolversOLD/conscale.c \
../plugins/ampl/3rd/amplsolversOLD/conval.c \
../plugins/ampl/3rd/amplsolversOLD/degree.c \
../plugins/ampl/3rd/amplsolversOLD/derprop.c \
../plugins/ampl/3rd/amplsolversOLD/dtoa.c \
../plugins/ampl/3rd/amplsolversOLD/dtoa1.c \
../plugins/ampl/3rd/amplsolversOLD/duthes.c \
../plugins/ampl/3rd/amplsolversOLD/dynlink.c \
../plugins/ampl/3rd/amplsolversOLD/f_read.c \
../plugins/ampl/3rd/amplsolversOLD/fg_read.c \
../plugins/ampl/3rd/amplsolversOLD/fg_write.c \
../plugins/ampl/3rd/amplsolversOLD/fgh_read.c \
../plugins/ampl/3rd/amplsolversOLD/fpecatch.c \
../plugins/ampl/3rd/amplsolversOLD/fpinit.c \
../plugins/ampl/3rd/amplsolversOLD/fpinitmt.c \
../plugins/ampl/3rd/amplsolversOLD/fullhes.c \
../plugins/ampl/3rd/amplsolversOLD/func_add.c \
../plugins/ampl/3rd/amplsolversOLD/funcadd.c \
../plugins/ampl/3rd/amplsolversOLD/funcadd0.c \
../plugins/ampl/3rd/amplsolversOLD/funcadd1.c \
../plugins/ampl/3rd/amplsolversOLD/funcaddk.c \
../plugins/ampl/3rd/amplsolversOLD/funcaddr.c \
../plugins/ampl/3rd/amplsolversOLD/g_fmt.c \
../plugins/ampl/3rd/amplsolversOLD/genrowno.c \
../plugins/ampl/3rd/amplsolversOLD/getenv.c \
../plugins/ampl/3rd/amplsolversOLD/getstub.c \
../plugins/ampl/3rd/amplsolversOLD/htcl.c \
../plugins/ampl/3rd/amplsolversOLD/indic_cons.c \
../plugins/ampl/3rd/amplsolversOLD/jac0dim.c \
../plugins/ampl/3rd/amplsolversOLD/jac2dim.c \
../plugins/ampl/3rd/amplsolversOLD/jacdim.c \
../plugins/ampl/3rd/amplsolversOLD/jacinc.c \
../plugins/ampl/3rd/amplsolversOLD/jacinc1.c \
../plugins/ampl/3rd/amplsolversOLD/libnamsave.c \
../plugins/ampl/3rd/amplsolversOLD/mach.c \
../plugins/ampl/3rd/amplsolversOLD/mainexit.c \
../plugins/ampl/3rd/amplsolversOLD/mip_pri.c \
../plugins/ampl/3rd/amplsolversOLD/misc.c \
../plugins/ampl/3rd/amplsolversOLD/mpec_adj.c \
../plugins/ampl/3rd/amplsolversOLD/mpec_adj0.c \
../plugins/ampl/3rd/amplsolversOLD/mqpcheckv.c \
../plugins/ampl/3rd/amplsolversOLD/mypow.c \
../plugins/ampl/3rd/amplsolversOLD/names.c \
../plugins/ampl/3rd/amplsolversOLD/nl_obj.c \
../plugins/ampl/3rd/amplsolversOLD/nqpcheck.c \
../plugins/ampl/3rd/amplsolversOLD/nqpcheckZ.c \
../plugins/ampl/3rd/amplsolversOLD/obj2val.c \
../plugins/ampl/3rd/amplsolversOLD/obj_adj.c \
../plugins/ampl/3rd/amplsolversOLD/obj_adj0.c \
../plugins/ampl/3rd/amplsolversOLD/obj_prec.c \
../plugins/ampl/3rd/amplsolversOLD/objconst.c \
../plugins/ampl/3rd/amplsolversOLD/objval.c \
../plugins/ampl/3rd/amplsolversOLD/objval_.c \
../plugins/ampl/3rd/amplsolversOLD/op_type.c \
../plugins/ampl/3rd/amplsolversOLD/pfg_read.c \
../plugins/ampl/3rd/amplsolversOLD/pfghread.c \
../plugins/ampl/3rd/amplsolversOLD/printf.c \
../plugins/ampl/3rd/amplsolversOLD/pshvprod.c \
../plugins/ampl/3rd/amplsolversOLD/punknown.c \
../plugins/ampl/3rd/amplsolversOLD/qp_read.c \
../plugins/ampl/3rd/amplsolversOLD/qpcheck.c \
../plugins/ampl/3rd/amplsolversOLD/qpcheckZ.c \
../plugins/ampl/3rd/amplsolversOLD/qsortv.c \
../plugins/ampl/3rd/amplsolversOLD/readsol.c \
../plugins/ampl/3rd/amplsolversOLD/repwhere.c \
../plugins/ampl/3rd/amplsolversOLD/rops.c \
../plugins/ampl/3rd/amplsolversOLD/rops2.c \
../plugins/ampl/3rd/amplsolversOLD/sigcatch.c \
../plugins/ampl/3rd/amplsolversOLD/sjac0dim.c \
../plugins/ampl/3rd/amplsolversOLD/sos_add.c \
../plugins/ampl/3rd/amplsolversOLD/sphes.c \
../plugins/ampl/3rd/amplsolversOLD/sprintf.c \
../plugins/ampl/3rd/amplsolversOLD/sscanf.c \
../plugins/ampl/3rd/amplsolversOLD/stderr.c \
../plugins/ampl/3rd/amplsolversOLD/strerror.c \
../plugins/ampl/3rd/amplsolversOLD/studchk0.c \
../plugins/ampl/3rd/amplsolversOLD/suf_sos.c \
../plugins/ampl/3rd/amplsolversOLD/value.c \
../plugins/ampl/3rd/amplsolversOLD/writesol.c \
../plugins/ampl/3rd/amplsolversOLD/wrtsol_.c \
../plugins/ampl/3rd/amplsolversOLD/ws_desc.c \
../plugins/ampl/3rd/amplsolversOLD/wsu_desc.c \
../plugins/ampl/3rd/amplsolversOLD/x2check.c \
../plugins/ampl/3rd/amplsolversOLD/xectim.c \
../plugins/ampl/3rd/amplsolversOLD/xp1known.c \
../plugins/ampl/3rd/amplsolversOLD/xp2known.c 

OBJS += \
./plugins/ampl/3rd/amplsolversOLD/arithchk.o \
./plugins/ampl/3rd/amplsolversOLD/asldate.o \
./plugins/ampl/3rd/amplsolversOLD/atof.o \
./plugins/ampl/3rd/amplsolversOLD/auxinfo.o \
./plugins/ampl/3rd/amplsolversOLD/avltree.o \
./plugins/ampl/3rd/amplsolversOLD/b_search.o \
./plugins/ampl/3rd/amplsolversOLD/basename.o \
./plugins/ampl/3rd/amplsolversOLD/bscanf.o \
./plugins/ampl/3rd/amplsolversOLD/com2eval.o \
./plugins/ampl/3rd/amplsolversOLD/comeval.o \
./plugins/ampl/3rd/amplsolversOLD/con1ival.o \
./plugins/ampl/3rd/amplsolversOLD/con2ival.o \
./plugins/ampl/3rd/amplsolversOLD/con2val.o \
./plugins/ampl/3rd/amplsolversOLD/conadj.o \
./plugins/ampl/3rd/amplsolversOLD/conpval.o \
./plugins/ampl/3rd/amplsolversOLD/conscale.o \
./plugins/ampl/3rd/amplsolversOLD/conval.o \
./plugins/ampl/3rd/amplsolversOLD/degree.o \
./plugins/ampl/3rd/amplsolversOLD/derprop.o \
./plugins/ampl/3rd/amplsolversOLD/dtoa.o \
./plugins/ampl/3rd/amplsolversOLD/dtoa1.o \
./plugins/ampl/3rd/amplsolversOLD/duthes.o \
./plugins/ampl/3rd/amplsolversOLD/dynlink.o \
./plugins/ampl/3rd/amplsolversOLD/f_read.o \
./plugins/ampl/3rd/amplsolversOLD/fg_read.o \
./plugins/ampl/3rd/amplsolversOLD/fg_write.o \
./plugins/ampl/3rd/amplsolversOLD/fgh_read.o \
./plugins/ampl/3rd/amplsolversOLD/fpecatch.o \
./plugins/ampl/3rd/amplsolversOLD/fpinit.o \
./plugins/ampl/3rd/amplsolversOLD/fpinitmt.o \
./plugins/ampl/3rd/amplsolversOLD/fullhes.o \
./plugins/ampl/3rd/amplsolversOLD/func_add.o \
./plugins/ampl/3rd/amplsolversOLD/funcadd.o \
./plugins/ampl/3rd/amplsolversOLD/funcadd0.o \
./plugins/ampl/3rd/amplsolversOLD/funcadd1.o \
./plugins/ampl/3rd/amplsolversOLD/funcaddk.o \
./plugins/ampl/3rd/amplsolversOLD/funcaddr.o \
./plugins/ampl/3rd/amplsolversOLD/g_fmt.o \
./plugins/ampl/3rd/amplsolversOLD/genrowno.o \
./plugins/ampl/3rd/amplsolversOLD/getenv.o \
./plugins/ampl/3rd/amplsolversOLD/getstub.o \
./plugins/ampl/3rd/amplsolversOLD/htcl.o \
./plugins/ampl/3rd/amplsolversOLD/indic_cons.o \
./plugins/ampl/3rd/amplsolversOLD/jac0dim.o \
./plugins/ampl/3rd/amplsolversOLD/jac2dim.o \
./plugins/ampl/3rd/amplsolversOLD/jacdim.o \
./plugins/ampl/3rd/amplsolversOLD/jacinc.o \
./plugins/ampl/3rd/amplsolversOLD/jacinc1.o \
./plugins/ampl/3rd/amplsolversOLD/libnamsave.o \
./plugins/ampl/3rd/amplsolversOLD/mach.o \
./plugins/ampl/3rd/amplsolversOLD/mainexit.o \
./plugins/ampl/3rd/amplsolversOLD/mip_pri.o \
./plugins/ampl/3rd/amplsolversOLD/misc.o \
./plugins/ampl/3rd/amplsolversOLD/mpec_adj.o \
./plugins/ampl/3rd/amplsolversOLD/mpec_adj0.o \
./plugins/ampl/3rd/amplsolversOLD/mqpcheckv.o \
./plugins/ampl/3rd/amplsolversOLD/mypow.o \
./plugins/ampl/3rd/amplsolversOLD/names.o \
./plugins/ampl/3rd/amplsolversOLD/nl_obj.o \
./plugins/ampl/3rd/amplsolversOLD/nqpcheck.o \
./plugins/ampl/3rd/amplsolversOLD/nqpcheckZ.o \
./plugins/ampl/3rd/amplsolversOLD/obj2val.o \
./plugins/ampl/3rd/amplsolversOLD/obj_adj.o \
./plugins/ampl/3rd/amplsolversOLD/obj_adj0.o \
./plugins/ampl/3rd/amplsolversOLD/obj_prec.o \
./plugins/ampl/3rd/amplsolversOLD/objconst.o \
./plugins/ampl/3rd/amplsolversOLD/objval.o \
./plugins/ampl/3rd/amplsolversOLD/objval_.o \
./plugins/ampl/3rd/amplsolversOLD/op_type.o \
./plugins/ampl/3rd/amplsolversOLD/pfg_read.o \
./plugins/ampl/3rd/amplsolversOLD/pfghread.o \
./plugins/ampl/3rd/amplsolversOLD/printf.o \
./plugins/ampl/3rd/amplsolversOLD/pshvprod.o \
./plugins/ampl/3rd/amplsolversOLD/punknown.o \
./plugins/ampl/3rd/amplsolversOLD/qp_read.o \
./plugins/ampl/3rd/amplsolversOLD/qpcheck.o \
./plugins/ampl/3rd/amplsolversOLD/qpcheckZ.o \
./plugins/ampl/3rd/amplsolversOLD/qsortv.o \
./plugins/ampl/3rd/amplsolversOLD/readsol.o \
./plugins/ampl/3rd/amplsolversOLD/repwhere.o \
./plugins/ampl/3rd/amplsolversOLD/rops.o \
./plugins/ampl/3rd/amplsolversOLD/rops2.o \
./plugins/ampl/3rd/amplsolversOLD/sigcatch.o \
./plugins/ampl/3rd/amplsolversOLD/sjac0dim.o \
./plugins/ampl/3rd/amplsolversOLD/sos_add.o \
./plugins/ampl/3rd/amplsolversOLD/sphes.o \
./plugins/ampl/3rd/amplsolversOLD/sprintf.o \
./plugins/ampl/3rd/amplsolversOLD/sscanf.o \
./plugins/ampl/3rd/amplsolversOLD/stderr.o \
./plugins/ampl/3rd/amplsolversOLD/strerror.o \
./plugins/ampl/3rd/amplsolversOLD/studchk0.o \
./plugins/ampl/3rd/amplsolversOLD/suf_sos.o \
./plugins/ampl/3rd/amplsolversOLD/value.o \
./plugins/ampl/3rd/amplsolversOLD/writesol.o \
./plugins/ampl/3rd/amplsolversOLD/wrtsol_.o \
./plugins/ampl/3rd/amplsolversOLD/ws_desc.o \
./plugins/ampl/3rd/amplsolversOLD/wsu_desc.o \
./plugins/ampl/3rd/amplsolversOLD/x2check.o \
./plugins/ampl/3rd/amplsolversOLD/xectim.o \
./plugins/ampl/3rd/amplsolversOLD/xp1known.o \
./plugins/ampl/3rd/amplsolversOLD/xp2known.o 

C_DEPS += \
./plugins/ampl/3rd/amplsolversOLD/arithchk.d \
./plugins/ampl/3rd/amplsolversOLD/asldate.d \
./plugins/ampl/3rd/amplsolversOLD/atof.d \
./plugins/ampl/3rd/amplsolversOLD/auxinfo.d \
./plugins/ampl/3rd/amplsolversOLD/avltree.d \
./plugins/ampl/3rd/amplsolversOLD/b_search.d \
./plugins/ampl/3rd/amplsolversOLD/basename.d \
./plugins/ampl/3rd/amplsolversOLD/bscanf.d \
./plugins/ampl/3rd/amplsolversOLD/com2eval.d \
./plugins/ampl/3rd/amplsolversOLD/comeval.d \
./plugins/ampl/3rd/amplsolversOLD/con1ival.d \
./plugins/ampl/3rd/amplsolversOLD/con2ival.d \
./plugins/ampl/3rd/amplsolversOLD/con2val.d \
./plugins/ampl/3rd/amplsolversOLD/conadj.d \
./plugins/ampl/3rd/amplsolversOLD/conpval.d \
./plugins/ampl/3rd/amplsolversOLD/conscale.d \
./plugins/ampl/3rd/amplsolversOLD/conval.d \
./plugins/ampl/3rd/amplsolversOLD/degree.d \
./plugins/ampl/3rd/amplsolversOLD/derprop.d \
./plugins/ampl/3rd/amplsolversOLD/dtoa.d \
./plugins/ampl/3rd/amplsolversOLD/dtoa1.d \
./plugins/ampl/3rd/amplsolversOLD/duthes.d \
./plugins/ampl/3rd/amplsolversOLD/dynlink.d \
./plugins/ampl/3rd/amplsolversOLD/f_read.d \
./plugins/ampl/3rd/amplsolversOLD/fg_read.d \
./plugins/ampl/3rd/amplsolversOLD/fg_write.d \
./plugins/ampl/3rd/amplsolversOLD/fgh_read.d \
./plugins/ampl/3rd/amplsolversOLD/fpecatch.d \
./plugins/ampl/3rd/amplsolversOLD/fpinit.d \
./plugins/ampl/3rd/amplsolversOLD/fpinitmt.d \
./plugins/ampl/3rd/amplsolversOLD/fullhes.d \
./plugins/ampl/3rd/amplsolversOLD/func_add.d \
./plugins/ampl/3rd/amplsolversOLD/funcadd.d \
./plugins/ampl/3rd/amplsolversOLD/funcadd0.d \
./plugins/ampl/3rd/amplsolversOLD/funcadd1.d \
./plugins/ampl/3rd/amplsolversOLD/funcaddk.d \
./plugins/ampl/3rd/amplsolversOLD/funcaddr.d \
./plugins/ampl/3rd/amplsolversOLD/g_fmt.d \
./plugins/ampl/3rd/amplsolversOLD/genrowno.d \
./plugins/ampl/3rd/amplsolversOLD/getenv.d \
./plugins/ampl/3rd/amplsolversOLD/getstub.d \
./plugins/ampl/3rd/amplsolversOLD/htcl.d \
./plugins/ampl/3rd/amplsolversOLD/indic_cons.d \
./plugins/ampl/3rd/amplsolversOLD/jac0dim.d \
./plugins/ampl/3rd/amplsolversOLD/jac2dim.d \
./plugins/ampl/3rd/amplsolversOLD/jacdim.d \
./plugins/ampl/3rd/amplsolversOLD/jacinc.d \
./plugins/ampl/3rd/amplsolversOLD/jacinc1.d \
./plugins/ampl/3rd/amplsolversOLD/libnamsave.d \
./plugins/ampl/3rd/amplsolversOLD/mach.d \
./plugins/ampl/3rd/amplsolversOLD/mainexit.d \
./plugins/ampl/3rd/amplsolversOLD/mip_pri.d \
./plugins/ampl/3rd/amplsolversOLD/misc.d \
./plugins/ampl/3rd/amplsolversOLD/mpec_adj.d \
./plugins/ampl/3rd/amplsolversOLD/mpec_adj0.d \
./plugins/ampl/3rd/amplsolversOLD/mqpcheckv.d \
./plugins/ampl/3rd/amplsolversOLD/mypow.d \
./plugins/ampl/3rd/amplsolversOLD/names.d \
./plugins/ampl/3rd/amplsolversOLD/nl_obj.d \
./plugins/ampl/3rd/amplsolversOLD/nqpcheck.d \
./plugins/ampl/3rd/amplsolversOLD/nqpcheckZ.d \
./plugins/ampl/3rd/amplsolversOLD/obj2val.d \
./plugins/ampl/3rd/amplsolversOLD/obj_adj.d \
./plugins/ampl/3rd/amplsolversOLD/obj_adj0.d \
./plugins/ampl/3rd/amplsolversOLD/obj_prec.d \
./plugins/ampl/3rd/amplsolversOLD/objconst.d \
./plugins/ampl/3rd/amplsolversOLD/objval.d \
./plugins/ampl/3rd/amplsolversOLD/objval_.d \
./plugins/ampl/3rd/amplsolversOLD/op_type.d \
./plugins/ampl/3rd/amplsolversOLD/pfg_read.d \
./plugins/ampl/3rd/amplsolversOLD/pfghread.d \
./plugins/ampl/3rd/amplsolversOLD/printf.d \
./plugins/ampl/3rd/amplsolversOLD/pshvprod.d \
./plugins/ampl/3rd/amplsolversOLD/punknown.d \
./plugins/ampl/3rd/amplsolversOLD/qp_read.d \
./plugins/ampl/3rd/amplsolversOLD/qpcheck.d \
./plugins/ampl/3rd/amplsolversOLD/qpcheckZ.d \
./plugins/ampl/3rd/amplsolversOLD/qsortv.d \
./plugins/ampl/3rd/amplsolversOLD/readsol.d \
./plugins/ampl/3rd/amplsolversOLD/repwhere.d \
./plugins/ampl/3rd/amplsolversOLD/rops.d \
./plugins/ampl/3rd/amplsolversOLD/rops2.d \
./plugins/ampl/3rd/amplsolversOLD/sigcatch.d \
./plugins/ampl/3rd/amplsolversOLD/sjac0dim.d \
./plugins/ampl/3rd/amplsolversOLD/sos_add.d \
./plugins/ampl/3rd/amplsolversOLD/sphes.d \
./plugins/ampl/3rd/amplsolversOLD/sprintf.d \
./plugins/ampl/3rd/amplsolversOLD/sscanf.d \
./plugins/ampl/3rd/amplsolversOLD/stderr.d \
./plugins/ampl/3rd/amplsolversOLD/strerror.d \
./plugins/ampl/3rd/amplsolversOLD/studchk0.d \
./plugins/ampl/3rd/amplsolversOLD/suf_sos.d \
./plugins/ampl/3rd/amplsolversOLD/value.d \
./plugins/ampl/3rd/amplsolversOLD/writesol.d \
./plugins/ampl/3rd/amplsolversOLD/wrtsol_.d \
./plugins/ampl/3rd/amplsolversOLD/ws_desc.d \
./plugins/ampl/3rd/amplsolversOLD/wsu_desc.d \
./plugins/ampl/3rd/amplsolversOLD/x2check.d \
./plugins/ampl/3rd/amplsolversOLD/xectim.d \
./plugins/ampl/3rd/amplsolversOLD/xp1known.d \
./plugins/ampl/3rd/amplsolversOLD/xp2known.d 


# Each subdirectory must supply rules for building sources it contributes
plugins/ampl/3rd/amplsolversOLD/%.o: ../plugins/ampl/3rd/amplsolversOLD/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


