################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../plugins/ampl/3rd/amplsolvers/arithchk.c \
../plugins/ampl/3rd/amplsolvers/asldate.c \
../plugins/ampl/3rd/amplsolvers/atof.c \
../plugins/ampl/3rd/amplsolvers/auxinfo.c \
../plugins/ampl/3rd/amplsolvers/avltree.c \
../plugins/ampl/3rd/amplsolvers/b_search.c \
../plugins/ampl/3rd/amplsolvers/basename.c \
../plugins/ampl/3rd/amplsolvers/bscanf.c \
../plugins/ampl/3rd/amplsolvers/com2eval.c \
../plugins/ampl/3rd/amplsolvers/comeval.c \
../plugins/ampl/3rd/amplsolvers/con1ival.c \
../plugins/ampl/3rd/amplsolvers/con2ival.c \
../plugins/ampl/3rd/amplsolvers/con2val.c \
../plugins/ampl/3rd/amplsolvers/conadj.c \
../plugins/ampl/3rd/amplsolvers/conpval.c \
../plugins/ampl/3rd/amplsolvers/conscale.c \
../plugins/ampl/3rd/amplsolvers/conval.c \
../plugins/ampl/3rd/amplsolvers/degree.c \
../plugins/ampl/3rd/amplsolvers/derprop.c \
../plugins/ampl/3rd/amplsolvers/dtoa.c \
../plugins/ampl/3rd/amplsolvers/dtoa1.c \
../plugins/ampl/3rd/amplsolvers/duthes.c \
../plugins/ampl/3rd/amplsolvers/dynlink.c \
../plugins/ampl/3rd/amplsolvers/f_read.c \
../plugins/ampl/3rd/amplsolvers/fg_read.c \
../plugins/ampl/3rd/amplsolvers/fg_write.c \
../plugins/ampl/3rd/amplsolvers/fgh_read.c \
../plugins/ampl/3rd/amplsolvers/fpecatch.c \
../plugins/ampl/3rd/amplsolvers/fpinit.c \
../plugins/ampl/3rd/amplsolvers/fpinitmt.c \
../plugins/ampl/3rd/amplsolvers/fullhes.c \
../plugins/ampl/3rd/amplsolvers/func_add.c \
../plugins/ampl/3rd/amplsolvers/funcadd.c \
../plugins/ampl/3rd/amplsolvers/funcadd0.c \
../plugins/ampl/3rd/amplsolvers/funcadd1.c \
../plugins/ampl/3rd/amplsolvers/funcaddk.c \
../plugins/ampl/3rd/amplsolvers/funcaddr.c \
../plugins/ampl/3rd/amplsolvers/g_fmt.c \
../plugins/ampl/3rd/amplsolvers/genrowno.c \
../plugins/ampl/3rd/amplsolvers/getenv.c \
../plugins/ampl/3rd/amplsolvers/getstub.c \
../plugins/ampl/3rd/amplsolvers/htcl.c \
../plugins/ampl/3rd/amplsolvers/indic_cons.c \
../plugins/ampl/3rd/amplsolvers/jac0dim.c \
../plugins/ampl/3rd/amplsolvers/jac2dim.c \
../plugins/ampl/3rd/amplsolvers/jacdim.c \
../plugins/ampl/3rd/amplsolvers/jacinc.c \
../plugins/ampl/3rd/amplsolvers/jacinc1.c \
../plugins/ampl/3rd/amplsolvers/libnamsave.c \
../plugins/ampl/3rd/amplsolvers/mach.c \
../plugins/ampl/3rd/amplsolvers/mainexit.c \
../plugins/ampl/3rd/amplsolvers/mip_pri.c \
../plugins/ampl/3rd/amplsolvers/misc.c \
../plugins/ampl/3rd/amplsolvers/mpec_adj.c \
../plugins/ampl/3rd/amplsolvers/mpec_adj0.c \
../plugins/ampl/3rd/amplsolvers/mqpcheckv.c \
../plugins/ampl/3rd/amplsolvers/mypow.c \
../plugins/ampl/3rd/amplsolvers/names.c \
../plugins/ampl/3rd/amplsolvers/nl_obj.c \
../plugins/ampl/3rd/amplsolvers/nqpcheck.c \
../plugins/ampl/3rd/amplsolvers/nqpcheckZ.c \
../plugins/ampl/3rd/amplsolvers/obj2val.c \
../plugins/ampl/3rd/amplsolvers/obj_adj.c \
../plugins/ampl/3rd/amplsolvers/obj_adj0.c \
../plugins/ampl/3rd/amplsolvers/obj_prec.c \
../plugins/ampl/3rd/amplsolvers/objconst.c \
../plugins/ampl/3rd/amplsolvers/objval.c \
../plugins/ampl/3rd/amplsolvers/objval_.c \
../plugins/ampl/3rd/amplsolvers/op_type.c \
../plugins/ampl/3rd/amplsolvers/pfg_read.c \
../plugins/ampl/3rd/amplsolvers/pfghread.c \
../plugins/ampl/3rd/amplsolvers/printf.c \
../plugins/ampl/3rd/amplsolvers/pshvprod.c \
../plugins/ampl/3rd/amplsolvers/punknown.c \
../plugins/ampl/3rd/amplsolvers/qp_read.c \
../plugins/ampl/3rd/amplsolvers/qpcheck.c \
../plugins/ampl/3rd/amplsolvers/qpcheckZ.c \
../plugins/ampl/3rd/amplsolvers/qsortv.c \
../plugins/ampl/3rd/amplsolvers/readsol.c \
../plugins/ampl/3rd/amplsolvers/repwhere.c \
../plugins/ampl/3rd/amplsolvers/rops.c \
../plugins/ampl/3rd/amplsolvers/rops2.c \
../plugins/ampl/3rd/amplsolvers/sigcatch.c \
../plugins/ampl/3rd/amplsolvers/sjac0dim.c \
../plugins/ampl/3rd/amplsolvers/sos_add.c \
../plugins/ampl/3rd/amplsolvers/sphes.c \
../plugins/ampl/3rd/amplsolvers/sprintf.c \
../plugins/ampl/3rd/amplsolvers/sscanf.c \
../plugins/ampl/3rd/amplsolvers/stderr.c \
../plugins/ampl/3rd/amplsolvers/strerror.c \
../plugins/ampl/3rd/amplsolvers/studchk0.c \
../plugins/ampl/3rd/amplsolvers/suf_sos.c \
../plugins/ampl/3rd/amplsolvers/value.c \
../plugins/ampl/3rd/amplsolvers/writesol.c \
../plugins/ampl/3rd/amplsolvers/wrtsol_.c \
../plugins/ampl/3rd/amplsolvers/ws_desc.c \
../plugins/ampl/3rd/amplsolvers/wsu_desc.c \
../plugins/ampl/3rd/amplsolvers/x2check.c \
../plugins/ampl/3rd/amplsolvers/xectim.c \
../plugins/ampl/3rd/amplsolvers/xp1known.c \
../plugins/ampl/3rd/amplsolvers/xp2known.c 

OBJS += \
./plugins/ampl/3rd/amplsolvers/arithchk.o \
./plugins/ampl/3rd/amplsolvers/asldate.o \
./plugins/ampl/3rd/amplsolvers/atof.o \
./plugins/ampl/3rd/amplsolvers/auxinfo.o \
./plugins/ampl/3rd/amplsolvers/avltree.o \
./plugins/ampl/3rd/amplsolvers/b_search.o \
./plugins/ampl/3rd/amplsolvers/basename.o \
./plugins/ampl/3rd/amplsolvers/bscanf.o \
./plugins/ampl/3rd/amplsolvers/com2eval.o \
./plugins/ampl/3rd/amplsolvers/comeval.o \
./plugins/ampl/3rd/amplsolvers/con1ival.o \
./plugins/ampl/3rd/amplsolvers/con2ival.o \
./plugins/ampl/3rd/amplsolvers/con2val.o \
./plugins/ampl/3rd/amplsolvers/conadj.o \
./plugins/ampl/3rd/amplsolvers/conpval.o \
./plugins/ampl/3rd/amplsolvers/conscale.o \
./plugins/ampl/3rd/amplsolvers/conval.o \
./plugins/ampl/3rd/amplsolvers/degree.o \
./plugins/ampl/3rd/amplsolvers/derprop.o \
./plugins/ampl/3rd/amplsolvers/dtoa.o \
./plugins/ampl/3rd/amplsolvers/dtoa1.o \
./plugins/ampl/3rd/amplsolvers/duthes.o \
./plugins/ampl/3rd/amplsolvers/dynlink.o \
./plugins/ampl/3rd/amplsolvers/f_read.o \
./plugins/ampl/3rd/amplsolvers/fg_read.o \
./plugins/ampl/3rd/amplsolvers/fg_write.o \
./plugins/ampl/3rd/amplsolvers/fgh_read.o \
./plugins/ampl/3rd/amplsolvers/fpecatch.o \
./plugins/ampl/3rd/amplsolvers/fpinit.o \
./plugins/ampl/3rd/amplsolvers/fpinitmt.o \
./plugins/ampl/3rd/amplsolvers/fullhes.o \
./plugins/ampl/3rd/amplsolvers/func_add.o \
./plugins/ampl/3rd/amplsolvers/funcadd.o \
./plugins/ampl/3rd/amplsolvers/funcadd0.o \
./plugins/ampl/3rd/amplsolvers/funcadd1.o \
./plugins/ampl/3rd/amplsolvers/funcaddk.o \
./plugins/ampl/3rd/amplsolvers/funcaddr.o \
./plugins/ampl/3rd/amplsolvers/g_fmt.o \
./plugins/ampl/3rd/amplsolvers/genrowno.o \
./plugins/ampl/3rd/amplsolvers/getenv.o \
./plugins/ampl/3rd/amplsolvers/getstub.o \
./plugins/ampl/3rd/amplsolvers/htcl.o \
./plugins/ampl/3rd/amplsolvers/indic_cons.o \
./plugins/ampl/3rd/amplsolvers/jac0dim.o \
./plugins/ampl/3rd/amplsolvers/jac2dim.o \
./plugins/ampl/3rd/amplsolvers/jacdim.o \
./plugins/ampl/3rd/amplsolvers/jacinc.o \
./plugins/ampl/3rd/amplsolvers/jacinc1.o \
./plugins/ampl/3rd/amplsolvers/libnamsave.o \
./plugins/ampl/3rd/amplsolvers/mach.o \
./plugins/ampl/3rd/amplsolvers/mainexit.o \
./plugins/ampl/3rd/amplsolvers/mip_pri.o \
./plugins/ampl/3rd/amplsolvers/misc.o \
./plugins/ampl/3rd/amplsolvers/mpec_adj.o \
./plugins/ampl/3rd/amplsolvers/mpec_adj0.o \
./plugins/ampl/3rd/amplsolvers/mqpcheckv.o \
./plugins/ampl/3rd/amplsolvers/mypow.o \
./plugins/ampl/3rd/amplsolvers/names.o \
./plugins/ampl/3rd/amplsolvers/nl_obj.o \
./plugins/ampl/3rd/amplsolvers/nqpcheck.o \
./plugins/ampl/3rd/amplsolvers/nqpcheckZ.o \
./plugins/ampl/3rd/amplsolvers/obj2val.o \
./plugins/ampl/3rd/amplsolvers/obj_adj.o \
./plugins/ampl/3rd/amplsolvers/obj_adj0.o \
./plugins/ampl/3rd/amplsolvers/obj_prec.o \
./plugins/ampl/3rd/amplsolvers/objconst.o \
./plugins/ampl/3rd/amplsolvers/objval.o \
./plugins/ampl/3rd/amplsolvers/objval_.o \
./plugins/ampl/3rd/amplsolvers/op_type.o \
./plugins/ampl/3rd/amplsolvers/pfg_read.o \
./plugins/ampl/3rd/amplsolvers/pfghread.o \
./plugins/ampl/3rd/amplsolvers/printf.o \
./plugins/ampl/3rd/amplsolvers/pshvprod.o \
./plugins/ampl/3rd/amplsolvers/punknown.o \
./plugins/ampl/3rd/amplsolvers/qp_read.o \
./plugins/ampl/3rd/amplsolvers/qpcheck.o \
./plugins/ampl/3rd/amplsolvers/qpcheckZ.o \
./plugins/ampl/3rd/amplsolvers/qsortv.o \
./plugins/ampl/3rd/amplsolvers/readsol.o \
./plugins/ampl/3rd/amplsolvers/repwhere.o \
./plugins/ampl/3rd/amplsolvers/rops.o \
./plugins/ampl/3rd/amplsolvers/rops2.o \
./plugins/ampl/3rd/amplsolvers/sigcatch.o \
./plugins/ampl/3rd/amplsolvers/sjac0dim.o \
./plugins/ampl/3rd/amplsolvers/sos_add.o \
./plugins/ampl/3rd/amplsolvers/sphes.o \
./plugins/ampl/3rd/amplsolvers/sprintf.o \
./plugins/ampl/3rd/amplsolvers/sscanf.o \
./plugins/ampl/3rd/amplsolvers/stderr.o \
./plugins/ampl/3rd/amplsolvers/strerror.o \
./plugins/ampl/3rd/amplsolvers/studchk0.o \
./plugins/ampl/3rd/amplsolvers/suf_sos.o \
./plugins/ampl/3rd/amplsolvers/value.o \
./plugins/ampl/3rd/amplsolvers/writesol.o \
./plugins/ampl/3rd/amplsolvers/wrtsol_.o \
./plugins/ampl/3rd/amplsolvers/ws_desc.o \
./plugins/ampl/3rd/amplsolvers/wsu_desc.o \
./plugins/ampl/3rd/amplsolvers/x2check.o \
./plugins/ampl/3rd/amplsolvers/xectim.o \
./plugins/ampl/3rd/amplsolvers/xp1known.o \
./plugins/ampl/3rd/amplsolvers/xp2known.o 

C_DEPS += \
./plugins/ampl/3rd/amplsolvers/arithchk.d \
./plugins/ampl/3rd/amplsolvers/asldate.d \
./plugins/ampl/3rd/amplsolvers/atof.d \
./plugins/ampl/3rd/amplsolvers/auxinfo.d \
./plugins/ampl/3rd/amplsolvers/avltree.d \
./plugins/ampl/3rd/amplsolvers/b_search.d \
./plugins/ampl/3rd/amplsolvers/basename.d \
./plugins/ampl/3rd/amplsolvers/bscanf.d \
./plugins/ampl/3rd/amplsolvers/com2eval.d \
./plugins/ampl/3rd/amplsolvers/comeval.d \
./plugins/ampl/3rd/amplsolvers/con1ival.d \
./plugins/ampl/3rd/amplsolvers/con2ival.d \
./plugins/ampl/3rd/amplsolvers/con2val.d \
./plugins/ampl/3rd/amplsolvers/conadj.d \
./plugins/ampl/3rd/amplsolvers/conpval.d \
./plugins/ampl/3rd/amplsolvers/conscale.d \
./plugins/ampl/3rd/amplsolvers/conval.d \
./plugins/ampl/3rd/amplsolvers/degree.d \
./plugins/ampl/3rd/amplsolvers/derprop.d \
./plugins/ampl/3rd/amplsolvers/dtoa.d \
./plugins/ampl/3rd/amplsolvers/dtoa1.d \
./plugins/ampl/3rd/amplsolvers/duthes.d \
./plugins/ampl/3rd/amplsolvers/dynlink.d \
./plugins/ampl/3rd/amplsolvers/f_read.d \
./plugins/ampl/3rd/amplsolvers/fg_read.d \
./plugins/ampl/3rd/amplsolvers/fg_write.d \
./plugins/ampl/3rd/amplsolvers/fgh_read.d \
./plugins/ampl/3rd/amplsolvers/fpecatch.d \
./plugins/ampl/3rd/amplsolvers/fpinit.d \
./plugins/ampl/3rd/amplsolvers/fpinitmt.d \
./plugins/ampl/3rd/amplsolvers/fullhes.d \
./plugins/ampl/3rd/amplsolvers/func_add.d \
./plugins/ampl/3rd/amplsolvers/funcadd.d \
./plugins/ampl/3rd/amplsolvers/funcadd0.d \
./plugins/ampl/3rd/amplsolvers/funcadd1.d \
./plugins/ampl/3rd/amplsolvers/funcaddk.d \
./plugins/ampl/3rd/amplsolvers/funcaddr.d \
./plugins/ampl/3rd/amplsolvers/g_fmt.d \
./plugins/ampl/3rd/amplsolvers/genrowno.d \
./plugins/ampl/3rd/amplsolvers/getenv.d \
./plugins/ampl/3rd/amplsolvers/getstub.d \
./plugins/ampl/3rd/amplsolvers/htcl.d \
./plugins/ampl/3rd/amplsolvers/indic_cons.d \
./plugins/ampl/3rd/amplsolvers/jac0dim.d \
./plugins/ampl/3rd/amplsolvers/jac2dim.d \
./plugins/ampl/3rd/amplsolvers/jacdim.d \
./plugins/ampl/3rd/amplsolvers/jacinc.d \
./plugins/ampl/3rd/amplsolvers/jacinc1.d \
./plugins/ampl/3rd/amplsolvers/libnamsave.d \
./plugins/ampl/3rd/amplsolvers/mach.d \
./plugins/ampl/3rd/amplsolvers/mainexit.d \
./plugins/ampl/3rd/amplsolvers/mip_pri.d \
./plugins/ampl/3rd/amplsolvers/misc.d \
./plugins/ampl/3rd/amplsolvers/mpec_adj.d \
./plugins/ampl/3rd/amplsolvers/mpec_adj0.d \
./plugins/ampl/3rd/amplsolvers/mqpcheckv.d \
./plugins/ampl/3rd/amplsolvers/mypow.d \
./plugins/ampl/3rd/amplsolvers/names.d \
./plugins/ampl/3rd/amplsolvers/nl_obj.d \
./plugins/ampl/3rd/amplsolvers/nqpcheck.d \
./plugins/ampl/3rd/amplsolvers/nqpcheckZ.d \
./plugins/ampl/3rd/amplsolvers/obj2val.d \
./plugins/ampl/3rd/amplsolvers/obj_adj.d \
./plugins/ampl/3rd/amplsolvers/obj_adj0.d \
./plugins/ampl/3rd/amplsolvers/obj_prec.d \
./plugins/ampl/3rd/amplsolvers/objconst.d \
./plugins/ampl/3rd/amplsolvers/objval.d \
./plugins/ampl/3rd/amplsolvers/objval_.d \
./plugins/ampl/3rd/amplsolvers/op_type.d \
./plugins/ampl/3rd/amplsolvers/pfg_read.d \
./plugins/ampl/3rd/amplsolvers/pfghread.d \
./plugins/ampl/3rd/amplsolvers/printf.d \
./plugins/ampl/3rd/amplsolvers/pshvprod.d \
./plugins/ampl/3rd/amplsolvers/punknown.d \
./plugins/ampl/3rd/amplsolvers/qp_read.d \
./plugins/ampl/3rd/amplsolvers/qpcheck.d \
./plugins/ampl/3rd/amplsolvers/qpcheckZ.d \
./plugins/ampl/3rd/amplsolvers/qsortv.d \
./plugins/ampl/3rd/amplsolvers/readsol.d \
./plugins/ampl/3rd/amplsolvers/repwhere.d \
./plugins/ampl/3rd/amplsolvers/rops.d \
./plugins/ampl/3rd/amplsolvers/rops2.d \
./plugins/ampl/3rd/amplsolvers/sigcatch.d \
./plugins/ampl/3rd/amplsolvers/sjac0dim.d \
./plugins/ampl/3rd/amplsolvers/sos_add.d \
./plugins/ampl/3rd/amplsolvers/sphes.d \
./plugins/ampl/3rd/amplsolvers/sprintf.d \
./plugins/ampl/3rd/amplsolvers/sscanf.d \
./plugins/ampl/3rd/amplsolvers/stderr.d \
./plugins/ampl/3rd/amplsolvers/strerror.d \
./plugins/ampl/3rd/amplsolvers/studchk0.d \
./plugins/ampl/3rd/amplsolvers/suf_sos.d \
./plugins/ampl/3rd/amplsolvers/value.d \
./plugins/ampl/3rd/amplsolvers/writesol.d \
./plugins/ampl/3rd/amplsolvers/wrtsol_.d \
./plugins/ampl/3rd/amplsolvers/ws_desc.d \
./plugins/ampl/3rd/amplsolvers/wsu_desc.d \
./plugins/ampl/3rd/amplsolvers/x2check.d \
./plugins/ampl/3rd/amplsolvers/xectim.d \
./plugins/ampl/3rd/amplsolvers/xp1known.d \
./plugins/ampl/3rd/amplsolvers/xp2known.d 


# Each subdirectory must supply rules for building sources it contributes
plugins/ampl/3rd/amplsolvers/%.o: ../plugins/ampl/3rd/amplsolvers/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


