function (lib_full_path var libdir libname)
  if (BUILD_SHARED_LIBS)
    set (_pre ${CMAKE_SHARED_LIBRARY_PREFIX})
    set (_suf ${CMAKE_SHARED_LIBRARY_SUFFIX})
  else ()
    set (_pre ${CMAKE_STATIC_LIBRARY_PREFIX})
    set (_suf ${CMAKE_STATIC_LIBRARY_SUFFIX})
  endif ()
  set (${var} "${libdir}/${_pre}${libname}${_suf}" PARENT_SCOPE)
endfunction ()
