#! /usr/bin/env python
# encoding: utf-8

def build (bld):

	bld.program (
		target = "optimizer02",
		use = "ibex soplex interval jni gaol mathlib gdtoa ultim",
		cxxflags = "-O3 -DNDEBUG -Wno-deprecated",
		source = "optimizer02.cpp"
	)

