#! /usr/bin/env python
# encoding: utf-8

import ibexutils
import shutil, os

def configure (conf):
	# Add all subdirectories of the 'src' directory in srcnode and bldnode in the
	# includes
	subdir = ibexutils.get_dirlist (conf.path)
	snode = conf.srcnode.make_node ("src")
	bnode = conf.bldnode.make_node ("src")
	for p in subdir:
		conf.env.append_unique ("INCLUDES_IBEX", snode.make_node(p).abspath())
		conf.env.append_unique ("INCLUDES_IBEX", bnode.make_node(p).abspath())

	# Set env variable containing the list of all ibex source files (by looking
	# recursively for all files ending with '.cpp' or '.yc' o '.l')
	ibex_src = conf.path.ant_glob ("**/*.(cpp|yc|l)")
	ibex_src =[ f.path_from (conf.path) for f in ibex_src ]
	conf.env.append_unique ('IBEX_SRC', ibex_src)

	# Set env variable containing the list of all ibex headers (by looking
	# recursively for all files starting with 'ibex_' and ending with '.h' or
	# '.h_')
	ibex_hdr = conf.path.ant_glob ("**/ibex_*.h **/ibex_*.h_")
	ibex_hdr =[ f.path_from (conf.path) for f in ibex_hdr ]
	conf.env.append_unique ('IBEX_HDR', ibex_hdr)

def build (bld):
	# c++ compilation of main lib
	tg_ibex = (bld.shlib if bld.env.ENABLE_SHARED else bld.stlib) (
		target = "ibex",
		use  = [ "IBEX", "ITV_LIB" ] + bld.env.IBEX_PLUGIN_USE_LIST,
		source = bld.env.IBEX_SRC,
		install_path = bld.env.LIBDIR,
	)

	# install headers
	bld.install_files (bld.env.INCDIR_HDR, bld.env.IBEX_HDR)
