name: Build with CMake

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ \
          gcc \
          flex \
          bison \
          python2.7 \
          make \
          pkg-config

    - name: Create build directory and compile
      run: |
        mkdir build
        cd build
        cmake ..
        make
