name: Tests
on: push
env:
  CHECKSUM: 23793d9ac4d6ab79e5f928f8630854dbfe8f6815b334a0006d4e2da82974abeffca4651f931384a09fb4a2c06d6cd4345d91f2452d8e7919a2735f7dc4cc170c
jobs:
  linux-cmake-build-and-check:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          apt update
          apt install -y gcc g++ cmake flex bison libcppunit-dev patch
      - name: CMake
        run: |
          mkdir build
          cd build
          cmake -DINTERVAL_LIB=${{ matrix.interval_lib }} -DBUILD_JAVA_INTERFACE=ON -DBUILD_SHARED_LIBS=ON -DLP_LIB=${{ matrix.lp_lib }} ..
      - name: make
        run: |
          cd build
          make
      - name: make check
        run: |
          cd build
          make check
    strategy:
      matrix:
        interval_lib: [gaol, filib]
        lp_lib: [soplex]

  macos-cmake-build-and-check:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          brew update
#          brew install cppunit
      - name: CMake
        run: |
          mkdir build
          cd build
          cmake -DINTERVAL_LIB=${{ matrix.interval_lib }} -DBUILD_JAVA_INTERFACE=ON -DBUILD_SHARED_LIBS=ON -DLP_LIB=${{ matrix.lp_lib }} ..
      - name: make
        run: |
          cd build
          make
      - name: ibexsolve
        run: |
          export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/ibex/3rd
          cd /Users/runner/work/ibex-lib/ibex-lib/build/bin/
          ./ibexsolve -v
#     - name: make check
#       run: |
#         cd build
#         make check
    strategy:
      matrix:
        interval_lib: [filib]
        lp_lib: [soplex]
