name: Tests
on: push
env:
  CHECKSUM: 23793d9ac4d6ab79e5f928f8630854dbfe8f6815b334a0006d4e2da82974abeffca4651f931384a09fb4a2c06d6cd4345d91f2452d8e7919a2735f7dc4cc170c
jobs:
  cmake-build-and-check:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          apt update
          apt install -y gcc g++ cmake flex bison libcppunit-dev patch
      - name: CMake
        run: |
          mkdir build
          cd build
          cmake -DINTERVAL_LIB=${{ matrix.interval_lib }} -DLP_LIB=${{ matrix.lp_lib }} ..
      - name: make
        run: |
          cd build
          make
      - name: make check
        run: |
          cd build
          make check
    strategy:
      matrix:
        interval_lib: [gaol, filib]
        lp_lib: [none, soplex]
