name: Tests MacOS
on: push
jobs:
  macos-cmake-build-and-check:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          brew update
          brew install cppunit pkg-config
      - name: CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/Users/runner/work/ibex-lib/ibex-lib -DINTERVAL_LIB=${{ matrix.interval_lib }} -DBUILD_JAVA_INTERFACE=ON -DBUILD_SHARED_LIBS=ON -DLP_LIB=${{ matrix.lp_lib }} ..
      - name: make
        run: |
          cd build
          make install
      - name: check_itv
        run: |
          cd examples
          export PKG_CONFIG_PATH=/Users/runner/work/ibex-lib/ibex-lib/share/pkgconfig
          make check_itv
          export DYLD_LIBRARY_PATH=/Users/runner/work/ibex-lib/ibex-lib/lib/:/Users/runner/work/ibex-lib/ibex-lib/lib/ibex/3rd
          ./check_itv
      - name: ibexsolve
        run: |
          cd build/bin/
          ./ibexsolve -v
      - name: make check
        run: |
          cd build
          make check
    strategy:
      matrix:
        interval_lib: [gaol]
#	interval_lib: [gaol,filib]
        lp_lib: [soplex]
